discord_webhook_url = ENV['DISCORD_WEBHOOK_URL']
discord_message = "Build tests passed successfully"
test_is_passed = true

desc 'Сборка тестов'
lane :build_for_testing do
    cocoapods
    scan(
      derived_data_path: "DerivedData",
      build_for_testing: true
    )
end

desc 'Запуск тестов'
lane :run_tests_without_building do
    scan(
      derived_data_path: "DerivedData",
      test_without_building: true
    )
end

desc 'Запуск тестов'
lane :build_and_test do
  build_for_testing
  run_tests_without_building
  discord
rescue => ex
  discord_message = "Build tests failed"
  test_is_passed = false
  discord
end

desc 'Уведомление в Discord'
lane :discord do
  result = bool_to_word(test_is_passed)

  discord_notifier(
    webhook_url: discord_webhook_url,
    title: "chatterbox",
    description: discord_message,
    success: result,
    thumbnail_url: "https://acdn.tinkoff.ru/static/documents/80f3f5f9-eabc-4b45-9c5f-30c048a8a756.png"
  )
end

def bool_to_word(bool)
 return bool ? "true" : "false"
end
