discord_webhook_url = ENV['DISCORD_WEBHOOK_URL']
discord_message = "Build tests passed successfully"

desc 'Сборка тестов'
lane :build_for_testing do
    cocoapods
    scan(
      derived_data_path: "DerivedData",
      build_for_testing: true
    )
end

desc 'Запуск тестов'
lane :run_tests do
    scan(
      derived_data_path: "DerivedData",
      test_without_building: true
    )
end

desc 'Запуск тестов'
lane :build_and_test do
  build_for_testing
  run_tests
  discord
rescue => ex
  discord_message = "Build tests failed"
  discord
end

desc 'Уведомление в Discord'
lane :discord do
  discord_notifier(
    webhook_url: discord_webhook_url,
    title: "chatterbox",
    description: discord_message
  )
end
